"""Editable bilingual retrieval configuration. Regexes only scope negation, not retrieval."""
from .models import ScreeningCriterion

AE = r"adverse|side effect|toxicity|colitis|rash|hepatitis|nausea|complication|symptom|develop|pneumonitis|liver injury|unerwünscht|nebenwirkung|beschwerd|entwickelt|kolitis|hautreaktion|hautausschlag|leberschädigung|toxizität|komplikation"

# ID, label, English queries, German queries, English/German QA questions, negation concepts.
DEFINITIONS = [
    ("drug", "Drug or medicinal product mentioned",
     ["medicinal product used by the patient", "medication administered to the patient", "drug exposure"],
     ["Arzneimittel beim Patienten", "verabreichtes Medikament", "Arzneimittelexposition", "Behandlung mit einem Medikament"],
     "Which drug was mentioned?", "Welches Arzneimittel wurde erwähnt?", r"drug|medication|treatment|received|administer|arzneimittel|medikament|behandlung|verabreich|erhielt"),
    ("event", "Adverse event or adverse drug reaction",
     ["adverse event experienced by the patient", "adverse drug reaction", "treatment related toxicity", "patient developed symptoms after medication"],
     ["unerwünschtes Ereignis beim Patienten", "unerwünschte Arzneimittelwirkung", "Nebenwirkung nach der Behandlung", "Patient entwickelte Beschwerden nach der Behandlung"],
     "What adverse event did the patient experience?", "Welche Nebenwirkung entwickelte der Patient?", AE),
    ("human", "Human patient or human study",
     ["human patient", "patient treated with medication", "individual patient case"],
     ["menschlicher Patient", "behandelter Patient", "individueller Patientenfall"],
     "Who was the patient?", "Wer war der Patient?", r"patient|human|participant|woman|man|male|female|mensch|teilnehmer|frau|mann"),
    ("exposure", "Drug exposure",
     ["patient received drug treatment", "medication was administered to the patient"],
     ["Der Patient erhielt eine Arzneimittelbehandlung", "Das Medikament wurde verabreicht", "Arzneimittelexposition"],
     "What medication did the patient receive?", "Welches Medikament erhielt der Patient?", r"received|administer|exposure|treatment|drug|erhielt|verabreich|exposition|behandlung|medikament"),
    ("temporal", "Temporal relationship",
     ["adverse event occurred after drug administration", "symptoms developed after treatment"],
     ["unerwünschtes Ereignis nach Arzneimittelgabe", "Symptome traten nach der Behandlung auf", "Beschwerden entwickelten sich nach der Medikamenteneinnahme"],
     "When did symptoms begin relative to treatment?", "Wann traten die Symptome nach der Behandlung auf?", AE + r"|after|before|following|nach|vor|beginn"),
    ("relationship", "Suspected drug-event relationship",
     ["adverse event associated with the drug", "suspected drug related reaction", "treatment caused the adverse event"],
     ["unerwünschtes Ereignis im Zusammenhang mit dem Arzneimittel", "Verdacht auf arzneimittelbedingte Reaktion", "Nebenwirkung im Zusammenhang mit der Behandlung"],
     "What drug-event relationship was suspected?", "Welcher Zusammenhang mit dem Arzneimittel wurde vermutet?", r"associat|caus|attribut|relat|suspect|zusammenhang|verursach|bedingt|verdacht|vermut"),
    ("serious", "Serious adverse event",
     ["serious adverse event", "serious adverse event required hospitalization", "life threatening fatal reaction disability death"],
     ["schwerwiegendes unerwünschtes Ereignis", "lebensbedrohliche Nebenwirkung mit Krankenhausaufenthalt", "tödliche Reaktion oder bleibende Behinderung"],
     "What serious outcome occurred?", "Welche schwerwiegende Folge trat auf?", r"serious|hospital|death|fatal|life.threat|disab|schwerwiegend|krankenhaus|stationär|tod|tödlich|lebensbedroh|behinder"),
    ("outcome", "Patient outcome",
     ["patient recovered symptoms resolved", "patient outcome died improved persistent symptoms"],
     ["Der Patient erholte sich und die Symptome klangen ab", "Verlauf mit Besserung oder anhaltenden Beschwerden"],
     "What was the patient outcome?", "Wie war der Ausgang beim Patienten?", r"recover|resolv|died|improv|outcome|persist|erholt|erholung|abklang|klangen|besser|verlauf|verstarb|anhalt"),
    ("withdrawal", "Drug withdrawal or discontinuation",
     ["medication was discontinued withdrawn", "treatment was stopped due to adverse reaction"],
     ["Das Medikament wurde abgesetzt", "Die Behandlung wurde wegen einer Nebenwirkung abgebrochen"],
     "Was treatment discontinued?", "Wurde die Behandlung abgesetzt?", r"discontinu|withdraw|stop|cessation|abgesetzt|absetz|abgebroch|abbruch|beendet"),
    ("dechallenge", "Dechallenge information",
     ["symptoms improved after stopping the drug", "positive negative dechallenge following withdrawal"],
     ["Die Symptome besserten sich nach Absetzen des Medikaments", "Dechallenge nach Absetzen des Arzneimittels"],
     "What happened after stopping the drug?", "Was geschah nach Absetzen des Medikaments?", r"dechallenge|improv|resolv|withdraw|stop|besser|absetz|abgesetzt|abklang|klangen"),
    ("rechallenge", "Rechallenge information",
     ["symptoms recurred when drug was restarted", "rechallenge reintroduction of medication"],
     ["Die Symptome traten nach erneuter Gabe wieder auf", "Reexposition mit dem Arzneimittel", "Rechallenge nach Wiederaufnahme der Behandlung"],
     "What happened when the drug was restarted?", "Was geschah nach erneuter Gabe des Arzneimittels?", r"rechallenge|restart|reintroduc|recur|reexposition|erneut|wiederaufnahme|wieder auf"),
    ("dose", "Dose information",
     ["drug dose milligrams daily dosage", "patient received mg per kilogram"],
     ["Dosierung des Arzneimittels in Milligramm täglich", "Der Patient erhielt mg pro Kilogramm"],
     "What dose was administered?", "Welche Dosis wurde verabreicht?", r"dose|dosage|mg|mcg|milligram|dosis|dosierung"),
    ("age", "Patient age", ["patient aged years old", "age of the patient"],
     ["Alter des Patienten in Jahren", "jähriger Patient"],
     "How old was the patient?", "Wie alt war der Patient?", r"age|year|month.old|alter|jahre|jährig|monate"),
    ("sex", "Patient sex", ["male female patient man woman"],
     ["männlicher oder weiblicher Patient", "Geschlecht des Patienten Mann oder Frau"],
     "What was the patient's sex?", "Welches Geschlecht hatte der Patient?", r"male|female|man|woman|boy|girl|sex|männlich|weiblich|mann|frau|geschlecht"),
    ("case", "Case report or individual patient", ["we report a case of a patient", "individual patient case presentation"],
     ["Fallbericht über einen einzelnen Patienten", "Fallbeschreibung eines individuellen Patientenfalls"],
     "What individual case was reported?", "Welcher einzelne Patientenfall wurde beschrieben?", r"case|patient|fallbericht|fallbeschreibung"),
    ("hospitalization", "Hospitalization", ["patient was hospitalized", "admitted to hospital following the adverse event"],
     ["Der Patient wurde ins Krankenhaus eingeliefert", "stationäre Aufnahme wegen der Nebenwirkung"],
     "Was the patient hospitalized?", "Wurde der Patient ins Krankenhaus eingeliefert?", r"hospital|admi|krankenhaus|stationär|eingeliefert"),
    ("death", "Death", ["the patient died", "fatal outcome after treatment"],
     ["Der Patient verstarb", "tödlicher Ausgang nach der Behandlung", "Tod des Patienten"],
     "Did the patient die?", "Ist der Patient verstorben?", r"died|death|fatal|dead|verstarb|verstorben|tod|tödlich|gestorben"),
]


def default_criteria():
    return [ScreeningCriterion(id=key, name=name, queries=en + de, question=question,
                               question_de=question_de, concepts=concepts)
            for key, name, en, de, question, question_de, concepts in DEFINITIONS]
