[server]
address = "127.0.0.1"
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#087E8B"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#EAF1F5"
textColor = "#153243"
font = "sans serif"
